name: mmoParty
main: mmo.Party.mmoParty
version: 0.13
website: http://forums.bukkit.org/threads/31055/
author: Rycochet <rycochet@rycochet.com>
depend: [mmoCore]

description: Simply "party" system for players. Single party leader, can invite others. When leader quits leadership falls to first invited etc. Uses Spout to display party members to everyone.
commands:
  party:
    description: Invites, leaves, promotes...
    aliases: [p,mmoparty]
    usage: /party help
