name: mmoParty
version: ${releaseVersion} b${buildNumber}
description: Provides leadership based parties with optional damage protection.
author: mmoMinecraftDev
website: http://mmo.me.uk

main: mmo.Party.MMOParty
depend: [Spout, mmoCore]
softdepend: [mmoChat]

commands:
    party:
        description: Invites, leaves, promotes...
        aliases: [p, mmoparty]
        usage: /party help
