name: mmoParty
main: mmo.Party.MMOParty
version: 1.1
website: http://forums.bukkit.org/threads/31055/
author: Rycochet <rycochet@rycochet.com>
database: true
depend: [mmoCore]
softdepend: [mmoChat]

description: Simply "party" system for players. Single party leader, can invite others. When leader quits leadership falls to first invited etc. Uses Spout to display party members to everyone.
commands:
  party:
    description: Invites, leaves, promotes...
    aliases: [p,mmoparty]
    usage: /party help
